#ifndef _ALTERA_HPS_SOC_SYSTEM_H_
#define _ALTERA_HPS_SOC_SYSTEM_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'dircc_system_node_dual_hps' in
 * file '../../fpga/dircc_system_node_dual_hps.sopcinfo'.
 */

/*
 * This file contains macros for module 'HPS' and devices
 * connected to the following master:
 *   h2f_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'node_1_processing_mem', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'NODE_1_PROCESSING_MEM_'.
 * The prefix is the slave descriptor.
 */
#define NODE_1_PROCESSING_MEM_COMPONENT_TYPE altera_avalon_onchip_memory2
#define NODE_1_PROCESSING_MEM_COMPONENT_NAME node_1_processing_mem
#define NODE_1_PROCESSING_MEM_BASE 0x0
#define NODE_1_PROCESSING_MEM_SPAN 40960
#define NODE_1_PROCESSING_MEM_END 0x9fff
#define NODE_1_PROCESSING_MEM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define NODE_1_PROCESSING_MEM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define NODE_1_PROCESSING_MEM_CONTENTS_INFO ""
#define NODE_1_PROCESSING_MEM_DUAL_PORT 1
#define NODE_1_PROCESSING_MEM_GUI_RAM_BLOCK_TYPE AUTO
#define NODE_1_PROCESSING_MEM_INIT_CONTENTS_FILE dircc_system_node_dual_node_0_processing_mem
#define NODE_1_PROCESSING_MEM_INIT_MEM_CONTENT 1
#define NODE_1_PROCESSING_MEM_INSTANCE_ID NONE
#define NODE_1_PROCESSING_MEM_NON_DEFAULT_INIT_FILE_ENABLED 1
#define NODE_1_PROCESSING_MEM_RAM_BLOCK_TYPE AUTO
#define NODE_1_PROCESSING_MEM_READ_DURING_WRITE_MODE OLD_DATA
#define NODE_1_PROCESSING_MEM_SINGLE_CLOCK_OP 1
#define NODE_1_PROCESSING_MEM_SIZE_MULTIPLE 1
#define NODE_1_PROCESSING_MEM_SIZE_VALUE 40960
#define NODE_1_PROCESSING_MEM_WRITABLE 1
#define NODE_1_PROCESSING_MEM_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define NODE_1_PROCESSING_MEM_MEMORY_INFO_GENERATE_DAT_SYM 1
#define NODE_1_PROCESSING_MEM_MEMORY_INFO_GENERATE_HEX 1
#define NODE_1_PROCESSING_MEM_MEMORY_INFO_HAS_BYTE_LANE 0
#define NODE_1_PROCESSING_MEM_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define NODE_1_PROCESSING_MEM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define NODE_1_PROCESSING_MEM_MEMORY_INFO_MEM_INIT_FILENAME dircc_system_node_dual_node_0_processing_mem

/*
 * Macros for device 'node_0_processing_mem', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'NODE_0_PROCESSING_MEM_'.
 * The prefix is the slave descriptor.
 */
#define NODE_0_PROCESSING_MEM_COMPONENT_TYPE altera_avalon_onchip_memory2
#define NODE_0_PROCESSING_MEM_COMPONENT_NAME node_0_processing_mem
#define NODE_0_PROCESSING_MEM_BASE 0x10000
#define NODE_0_PROCESSING_MEM_SPAN 40960
#define NODE_0_PROCESSING_MEM_END 0x19fff
#define NODE_0_PROCESSING_MEM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define NODE_0_PROCESSING_MEM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define NODE_0_PROCESSING_MEM_CONTENTS_INFO ""
#define NODE_0_PROCESSING_MEM_DUAL_PORT 1
#define NODE_0_PROCESSING_MEM_GUI_RAM_BLOCK_TYPE AUTO
#define NODE_0_PROCESSING_MEM_INIT_CONTENTS_FILE dircc_system_node_dual_node_0_processing_mem
#define NODE_0_PROCESSING_MEM_INIT_MEM_CONTENT 1
#define NODE_0_PROCESSING_MEM_INSTANCE_ID NONE
#define NODE_0_PROCESSING_MEM_NON_DEFAULT_INIT_FILE_ENABLED 1
#define NODE_0_PROCESSING_MEM_RAM_BLOCK_TYPE AUTO
#define NODE_0_PROCESSING_MEM_READ_DURING_WRITE_MODE OLD_DATA
#define NODE_0_PROCESSING_MEM_SINGLE_CLOCK_OP 1
#define NODE_0_PROCESSING_MEM_SIZE_MULTIPLE 1
#define NODE_0_PROCESSING_MEM_SIZE_VALUE 40960
#define NODE_0_PROCESSING_MEM_WRITABLE 1
#define NODE_0_PROCESSING_MEM_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define NODE_0_PROCESSING_MEM_MEMORY_INFO_GENERATE_DAT_SYM 1
#define NODE_0_PROCESSING_MEM_MEMORY_INFO_GENERATE_HEX 1
#define NODE_0_PROCESSING_MEM_MEMORY_INFO_HAS_BYTE_LANE 0
#define NODE_0_PROCESSING_MEM_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define NODE_0_PROCESSING_MEM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define NODE_0_PROCESSING_MEM_MEMORY_INFO_MEM_INIT_FILENAME dircc_system_node_dual_node_0_processing_mem


#endif /* _ALTERA_HPS_SOC_SYSTEM_H_ */
