# TCL File Generated by Component Editor 16.1
# Sun May 28 17:42:00 BST 2017
# DO NOT MODIFY


# 
# dircc_avalon_st_terminal "DiRCC Avalon-ST Terminal" v1.0
#  2017.05.28.17:42:00
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dircc_avalon_st_terminal
# 
set_module_property DESCRIPTION ""
set_module_property NAME dircc_avalon_st_terminal
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "DiRCC Avalon-ST Terminal"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dircc_avalon_st_terminal_inst
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file dircc_avalon_st_terminal.v VERILOG PATH dircc_avalon_st_terminal/dircc_avalon_st_terminal.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL dircc_avalon_st_terminal_inst
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file dircc_avalon_st_terminal.v VERILOG PATH dircc_avalon_st_terminal/dircc_avalon_st_terminal.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL dircc_avalon_st_terminal_inst
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file dircc_avalon_st_terminal.v VERILOG PATH dircc_avalon_st_terminal/dircc_avalon_st_terminal.sv


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point s1
# 
add_interface s1 avalon_streaming end
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 dataBitsPerSymbol 8
set_interface_property s1 errorDescriptor ""
set_interface_property s1 firstSymbolInHighOrderBits true
set_interface_property s1 maxChannel 0
set_interface_property s1 readyLatency 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 data data Input DATA_WIDTH
add_interface_port s1 empty empty Input 2
add_interface_port s1 endofpacket endofpacket Input 1
add_interface_port s1 ready ready Output 1
add_interface_port s1 startofpacket startofpacket Input 1
add_interface_port s1 valid valid Input 1


# 
# connection point status
# 
add_interface status avalon end
set_interface_property status addressUnits SYMBOLS
set_interface_property status associatedClock clock
set_interface_property status associatedReset reset
set_interface_property status bitsPerSymbol 8
set_interface_property status burstOnBurstBoundariesOnly false
set_interface_property status burstcountUnits SYMBOLS
set_interface_property status explicitAddressSpan 0
set_interface_property status holdTime 0
set_interface_property status linewrapBursts false
set_interface_property status maximumPendingReadTransactions 0
set_interface_property status maximumPendingWriteTransactions 0
set_interface_property status readLatency 0
set_interface_property status readWaitTime 1
set_interface_property status setupTime 0
set_interface_property status timingUnits Cycles
set_interface_property status writeWaitTime 0
set_interface_property status ENABLED true
set_interface_property status EXPORT_OF ""
set_interface_property status PORT_NAME_MAP ""
set_interface_property status CMSIS_SVD_VARIABLES ""
set_interface_property status SVD_ADDRESS_GROUP ""

add_interface_port status readdata readdata Output 16
add_interface_port status address address Input 1
add_interface_port status read_n read_n Input 1
set_interface_assignment status embeddedsw.configuration.isFlash 0
set_interface_assignment status embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment status embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment status embeddedsw.configuration.isPrintableDevice 0

