# TCL File Generated by Component Editor 16.1
# Tue Apr 11 18:02:18 BST 2017
# DO NOT MODIFY


# 
# dircc_address "DiRCC Address" v1.0
#  2017.04.11.18:02:18
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dircc_address
# 
set_module_property DESCRIPTION ""
set_module_property NAME dircc_address
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "DiRCC Address"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dircc_address_gen
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dircc_address_gen.sv SYSTEM_VERILOG PATH dircc_address_gen/dircc_address_gen.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL dircc_address_gen
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dircc_address_gen.sv SYSTEM_VERILOG PATH dircc_address_gen/dircc_address_gen.sv


# 
# parameters
# 
add_parameter ADDRESS INTEGER 0
set_parameter_property ADDRESS DEFAULT_VALUE 0
set_parameter_property ADDRESS DISPLAY_NAME ADDRESS
set_parameter_property ADDRESS TYPE INTEGER
set_parameter_property ADDRESS UNITS None
set_parameter_property ADDRESS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDRESS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point address_processing
# 
add_interface address_processing conduit end
set_interface_property address_processing associatedClock ""
set_interface_property address_processing associatedReset ""
set_interface_property address_processing ENABLED true
set_interface_property address_processing EXPORT_OF ""
set_interface_property address_processing PORT_NAME_MAP ""
set_interface_property address_processing CMSIS_SVD_VARIABLES ""
set_interface_property address_processing SVD_ADDRESS_GROUP ""

add_interface_port address_processing address_processing address Output 32


# 
# connection point address_routing
# 
add_interface address_routing conduit end
set_interface_property address_routing associatedClock ""
set_interface_property address_routing associatedReset ""
set_interface_property address_routing ENABLED true
set_interface_property address_routing EXPORT_OF ""
set_interface_property address_routing PORT_NAME_MAP ""
set_interface_property address_routing CMSIS_SVD_VARIABLES ""
set_interface_property address_routing SVD_ADDRESS_GROUP ""

add_interface_port address_routing address_routing address Output 32

