# TCL File Generated by Component Editor 16.1
# Sun Jun 04 19:54:56 BST 2017
# DO NOT MODIFY


# 
# dircc_router "DiRCC Router" v1.0
# Patrick Engelbert 2017.06.04.19:54:56
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dircc_router
# 
set_module_property DESCRIPTION ""
set_module_property NAME dircc_router
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Basic Functions/Bridges and Adaptors/Streaming"
set_module_property AUTHOR "Patrick Engelbert"
set_module_property DISPLAY_NAME "DiRCC Router"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dircc_router
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dircc_router.sv SYSTEM_VERILOG PATH dircc_router/dircc_router.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL dircc_router
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dircc_router.sv SYSTEM_VERILOG PATH dircc_router/dircc_router.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL dircc_router
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file dircc_router.sv SYSTEM_VERILOG PATH dircc_router/dircc_router.sv


# 
# parameters
# 
add_parameter SYMBOLS_PER_BEAT INTEGER 4 ""
set_parameter_property SYMBOLS_PER_BEAT DEFAULT_VALUE 4
set_parameter_property SYMBOLS_PER_BEAT DISPLAY_NAME SYMBOLS_PER_BEAT
set_parameter_property SYMBOLS_PER_BEAT WIDTH ""
set_parameter_property SYMBOLS_PER_BEAT TYPE INTEGER
set_parameter_property SYMBOLS_PER_BEAT UNITS None
set_parameter_property SYMBOLS_PER_BEAT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SYMBOLS_PER_BEAT DESCRIPTION ""
set_parameter_property SYMBOLS_PER_BEAT HDL_PARAMETER true
add_parameter BITS_PER_SYMBOL INTEGER 8
set_parameter_property BITS_PER_SYMBOL DEFAULT_VALUE 8
set_parameter_property BITS_PER_SYMBOL DISPLAY_NAME BITS_PER_SYMBOL
set_parameter_property BITS_PER_SYMBOL TYPE INTEGER
set_parameter_property BITS_PER_SYMBOL UNITS None
set_parameter_property BITS_PER_SYMBOL ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BITS_PER_SYMBOL HDL_PARAMETER true
add_parameter USE_PACKETS BOOLEAN true ""
set_parameter_property USE_PACKETS DEFAULT_VALUE true
set_parameter_property USE_PACKETS DISPLAY_NAME USE_PACKETS
set_parameter_property USE_PACKETS WIDTH ""
set_parameter_property USE_PACKETS TYPE BOOLEAN
set_parameter_property USE_PACKETS ENABLED false
set_parameter_property USE_PACKETS UNITS None
set_parameter_property USE_PACKETS DESCRIPTION ""
set_parameter_property USE_PACKETS HDL_PARAMETER true
add_parameter USE_EMPTY BOOLEAN true ""
set_parameter_property USE_EMPTY DEFAULT_VALUE true
set_parameter_property USE_EMPTY DISPLAY_NAME USE_EMPTY
set_parameter_property USE_EMPTY WIDTH ""
set_parameter_property USE_EMPTY TYPE BOOLEAN
set_parameter_property USE_EMPTY ENABLED false
set_parameter_property USE_EMPTY UNITS None
set_parameter_property USE_EMPTY DESCRIPTION ""
set_parameter_property USE_EMPTY HDL_PARAMETER true
add_parameter USE_HIGH_BIT_SELECT BOOLEAN true ""
set_parameter_property USE_HIGH_BIT_SELECT DEFAULT_VALUE true
set_parameter_property USE_HIGH_BIT_SELECT DISPLAY_NAME USE_HIGH_BIT_SELECT
set_parameter_property USE_HIGH_BIT_SELECT WIDTH ""
set_parameter_property USE_HIGH_BIT_SELECT TYPE BOOLEAN
set_parameter_property USE_HIGH_BIT_SELECT ENABLED false
set_parameter_property USE_HIGH_BIT_SELECT UNITS None
set_parameter_property USE_HIGH_BIT_SELECT DESCRIPTION ""
set_parameter_property USE_HIGH_BIT_SELECT HDL_PARAMETER true
add_parameter PIPELINE_READY INTEGER 1 ""
set_parameter_property PIPELINE_READY DEFAULT_VALUE 1
set_parameter_property PIPELINE_READY DISPLAY_NAME PIPELINE_READY
set_parameter_property PIPELINE_READY WIDTH ""
set_parameter_property PIPELINE_READY TYPE INTEGER
set_parameter_property PIPELINE_READY ENABLED false
set_parameter_property PIPELINE_READY UNITS None
set_parameter_property PIPELINE_READY ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PIPELINE_READY DESCRIPTION ""
set_parameter_property PIPELINE_READY HDL_PARAMETER true
add_parameter MAX_ROUTE_DIRECTION INTEGER 5 ""
set_parameter_property MAX_ROUTE_DIRECTION DEFAULT_VALUE 5
set_parameter_property MAX_ROUTE_DIRECTION DISPLAY_NAME MAX_ROUTE_DIRECTION
set_parameter_property MAX_ROUTE_DIRECTION WIDTH ""
set_parameter_property MAX_ROUTE_DIRECTION TYPE INTEGER
set_parameter_property MAX_ROUTE_DIRECTION ENABLED false
set_parameter_property MAX_ROUTE_DIRECTION UNITS None
set_parameter_property MAX_ROUTE_DIRECTION ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAX_ROUTE_DIRECTION DESCRIPTION ""
set_parameter_property MAX_ROUTE_DIRECTION HDL_PARAMETER true
add_parameter CHANNEL_WIDTH INTEGER 0 ""
set_parameter_property CHANNEL_WIDTH DEFAULT_VALUE 0
set_parameter_property CHANNEL_WIDTH DISPLAY_NAME CHANNEL_WIDTH
set_parameter_property CHANNEL_WIDTH WIDTH ""
set_parameter_property CHANNEL_WIDTH TYPE INTEGER
set_parameter_property CHANNEL_WIDTH UNITS None
set_parameter_property CHANNEL_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CHANNEL_WIDTH DESCRIPTION ""
set_parameter_property CHANNEL_WIDTH HDL_PARAMETER true
add_parameter maxChannel INTEGER 0 ""
set_parameter_property maxChannel DEFAULT_VALUE 0
set_parameter_property maxChannel DISPLAY_NAME maxChannel
set_parameter_property maxChannel TYPE INTEGER
set_parameter_property maxChannel UNITS None
set_parameter_property maxChannel ALLOWED_RANGES -2147483648:2147483647
set_parameter_property maxChannel DESCRIPTION ""
set_parameter_property maxChannel HDL_PARAMETER true
add_parameter ERROR_WIDTH INTEGER 0
set_parameter_property ERROR_WIDTH DEFAULT_VALUE 0
set_parameter_property ERROR_WIDTH DISPLAY_NAME ERROR_WIDTH
set_parameter_property ERROR_WIDTH TYPE INTEGER
set_parameter_property ERROR_WIDTH ENABLED false
set_parameter_property ERROR_WIDTH UNITS None
set_parameter_property ERROR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ERROR_WIDTH HDL_PARAMETER true


# 
# display items
# 
add_display_item "" "Functional Parameters" GROUP ""


# 
# connection point out
# 
add_interface out avalon_streaming start
set_interface_property out associatedClock clk
set_interface_property out associatedReset clk_reset
set_interface_property out dataBitsPerSymbol 8
set_interface_property out errorDescriptor ""
set_interface_property out firstSymbolInHighOrderBits true
set_interface_property out maxChannel 7
set_interface_property out readyLatency 0
set_interface_property out ENABLED true
set_interface_property out EXPORT_OF ""
set_interface_property out PORT_NAME_MAP ""
set_interface_property out CMSIS_SVD_VARIABLES ""
set_interface_property out SVD_ADDRESS_GROUP ""

add_interface_port out out_endofpacket endofpacket Output 1
add_interface_port out out_channel channel Output 3
add_interface_port out out_data data Output 32
add_interface_port out out_ready ready Input 1
add_interface_port out out_startofpacket startofpacket Output 1
add_interface_port out out_valid valid Output 1
add_interface_port out out_empty empty Output 2


# 
# connection point in
# 
add_interface in avalon_streaming end
set_interface_property in associatedClock clk
set_interface_property in associatedReset clk_reset
set_interface_property in dataBitsPerSymbol 8
set_interface_property in errorDescriptor ""
set_interface_property in firstSymbolInHighOrderBits true
set_interface_property in maxChannel 7
set_interface_property in readyLatency 0
set_interface_property in ENABLED true
set_interface_property in EXPORT_OF ""
set_interface_property in PORT_NAME_MAP ""
set_interface_property in CMSIS_SVD_VARIABLES ""
set_interface_property in SVD_ADDRESS_GROUP ""

add_interface_port in in_ready ready Output 1
add_interface_port in in_valid valid Input 1
add_interface_port in in_data data Input 32
add_interface_port in in_startofpacket startofpacket Input 1
add_interface_port in in_endofpacket endofpacket Input 1
add_interface_port in in_empty empty Input 2
add_interface_port in in_channel channel Input 3


# 
# connection point address
# 
add_interface address conduit end
set_interface_property address associatedClock ""
set_interface_property address associatedReset ""
set_interface_property address ENABLED true
set_interface_property address EXPORT_OF ""
set_interface_property address PORT_NAME_MAP ""
set_interface_property address CMSIS_SVD_VARIABLES ""
set_interface_property address SVD_ADDRESS_GROUP ""

add_interface_port address address address Input 32


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point clk_reset
# 
add_interface clk_reset reset end
set_interface_property clk_reset associatedClock clk
set_interface_property clk_reset synchronousEdges DEASSERT
set_interface_property clk_reset ENABLED true
set_interface_property clk_reset EXPORT_OF ""
set_interface_property clk_reset PORT_NAME_MAP ""
set_interface_property clk_reset CMSIS_SVD_VARIABLES ""
set_interface_property clk_reset SVD_ADDRESS_GROUP ""

add_interface_port clk_reset reset_n reset_n Input 1

