# TCL File Generated by Component Editor 16.1
# Mon Apr 10 13:16:18 BST 2017
# DO NOT MODIFY


# 
# dircc_router "DiRCC Router" v1.0
#  2017.04.10.13:16:18
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dircc_router
# 
set_module_property DESCRIPTION ""
set_module_property NAME dircc_router
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "DiRCC Router"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dircc_router
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dircc_router.sv SYSTEM_VERILOG PATH dircc_router/dircc_router.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL dircc_router
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file interface.sv SYSTEM_VERILOG PATH dircc_router/simulation/interface.sv
add_fileset_file test_read_write.sv SYSTEM_VERILOG PATH dircc_router/simulation/test_read_write.sv
add_fileset_file top.sv SYSTEM_VERILOG PATH dircc_router/simulation/top.sv
add_fileset_file dircc_router.sv SYSTEM_VERILOG PATH dircc_router/dircc_router.sv


# 
# parameters
# 
add_parameter SYMBOLS_PER_BEAT INTEGER 4 ""
set_parameter_property SYMBOLS_PER_BEAT DEFAULT_VALUE 4
set_parameter_property SYMBOLS_PER_BEAT DISPLAY_NAME SYMBOLS_PER_BEAT
set_parameter_property SYMBOLS_PER_BEAT WIDTH ""
set_parameter_property SYMBOLS_PER_BEAT TYPE INTEGER
set_parameter_property SYMBOLS_PER_BEAT UNITS None
set_parameter_property SYMBOLS_PER_BEAT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SYMBOLS_PER_BEAT DESCRIPTION ""
set_parameter_property SYMBOLS_PER_BEAT HDL_PARAMETER true
add_parameter BITS_PER_SYMBOL INTEGER 8
set_parameter_property BITS_PER_SYMBOL DEFAULT_VALUE 8
set_parameter_property BITS_PER_SYMBOL DISPLAY_NAME BITS_PER_SYMBOL
set_parameter_property BITS_PER_SYMBOL TYPE INTEGER
set_parameter_property BITS_PER_SYMBOL UNITS None
set_parameter_property BITS_PER_SYMBOL ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BITS_PER_SYMBOL HDL_PARAMETER true
add_parameter USE_PACKETS BOOLEAN true ""
set_parameter_property USE_PACKETS DEFAULT_VALUE true
set_parameter_property USE_PACKETS DISPLAY_NAME USE_PACKETS
set_parameter_property USE_PACKETS WIDTH ""
set_parameter_property USE_PACKETS TYPE BOOLEAN
set_parameter_property USE_PACKETS ENABLED false
set_parameter_property USE_PACKETS UNITS None
set_parameter_property USE_PACKETS DESCRIPTION ""
set_parameter_property USE_PACKETS HDL_PARAMETER true
add_parameter USE_EMPTY BOOLEAN true ""
set_parameter_property USE_EMPTY DEFAULT_VALUE true
set_parameter_property USE_EMPTY DISPLAY_NAME USE_EMPTY
set_parameter_property USE_EMPTY WIDTH ""
set_parameter_property USE_EMPTY TYPE BOOLEAN
set_parameter_property USE_EMPTY ENABLED false
set_parameter_property USE_EMPTY UNITS None
set_parameter_property USE_EMPTY DESCRIPTION ""
set_parameter_property USE_EMPTY HDL_PARAMETER true
add_parameter USE_HIGH_BIT_SELECT BOOLEAN true ""
set_parameter_property USE_HIGH_BIT_SELECT DEFAULT_VALUE true
set_parameter_property USE_HIGH_BIT_SELECT DISPLAY_NAME USE_HIGH_BIT_SELECT
set_parameter_property USE_HIGH_BIT_SELECT WIDTH ""
set_parameter_property USE_HIGH_BIT_SELECT TYPE BOOLEAN
set_parameter_property USE_HIGH_BIT_SELECT ENABLED false
set_parameter_property USE_HIGH_BIT_SELECT UNITS None
set_parameter_property USE_HIGH_BIT_SELECT DESCRIPTION ""
set_parameter_property USE_HIGH_BIT_SELECT HDL_PARAMETER true
add_parameter PIPELINE_READY INTEGER 1 ""
set_parameter_property PIPELINE_READY DEFAULT_VALUE 1
set_parameter_property PIPELINE_READY DISPLAY_NAME PIPELINE_READY
set_parameter_property PIPELINE_READY WIDTH ""
set_parameter_property PIPELINE_READY TYPE INTEGER
set_parameter_property PIPELINE_READY ENABLED false
set_parameter_property PIPELINE_READY UNITS None
set_parameter_property PIPELINE_READY ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PIPELINE_READY DESCRIPTION ""
set_parameter_property PIPELINE_READY HDL_PARAMETER true
add_parameter MAX_ROUTE_DIRECTION INTEGER 5 ""
set_parameter_property MAX_ROUTE_DIRECTION DEFAULT_VALUE 5
set_parameter_property MAX_ROUTE_DIRECTION DISPLAY_NAME MAX_ROUTE_DIRECTION
set_parameter_property MAX_ROUTE_DIRECTION WIDTH ""
set_parameter_property MAX_ROUTE_DIRECTION TYPE INTEGER
set_parameter_property MAX_ROUTE_DIRECTION ENABLED false
set_parameter_property MAX_ROUTE_DIRECTION UNITS None
set_parameter_property MAX_ROUTE_DIRECTION ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAX_ROUTE_DIRECTION DESCRIPTION ""
set_parameter_property MAX_ROUTE_DIRECTION HDL_PARAMETER true
add_parameter CHANNEL_WIDTH INTEGER 0 ""
set_parameter_property CHANNEL_WIDTH DEFAULT_VALUE 0
set_parameter_property CHANNEL_WIDTH DISPLAY_NAME CHANNEL_WIDTH
set_parameter_property CHANNEL_WIDTH WIDTH ""
set_parameter_property CHANNEL_WIDTH TYPE INTEGER
set_parameter_property CHANNEL_WIDTH ENABLED false
set_parameter_property CHANNEL_WIDTH UNITS None
set_parameter_property CHANNEL_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CHANNEL_WIDTH DESCRIPTION ""
set_parameter_property CHANNEL_WIDTH HDL_PARAMETER true
add_parameter ERROR_WIDTH INTEGER 0
set_parameter_property ERROR_WIDTH DEFAULT_VALUE 0
set_parameter_property ERROR_WIDTH DISPLAY_NAME ERROR_WIDTH
set_parameter_property ERROR_WIDTH TYPE INTEGER
set_parameter_property ERROR_WIDTH ENABLED false
set_parameter_property ERROR_WIDTH UNITS None
set_parameter_property ERROR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ERROR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point out
# 
add_interface out avalon_streaming start
set_interface_property out associatedClock clk_in
set_interface_property out associatedReset reset_in
set_interface_property out dataBitsPerSymbol 8
set_interface_property out errorDescriptor ""
set_interface_property out firstSymbolInHighOrderBits true
set_interface_property out maxChannel 0
set_interface_property out readyLatency 0
set_interface_property out ENABLED true
set_interface_property out EXPORT_OF ""
set_interface_property out PORT_NAME_MAP ""
set_interface_property out CMSIS_SVD_VARIABLES ""
set_interface_property out SVD_ADDRESS_GROUP ""

add_interface_port out out_endofpacket endofpacket Output 1
add_interface_port out out_channel channel Output 3
add_interface_port out out_data data Output 32
add_interface_port out out_ready ready Input 1
add_interface_port out out_startofpacket startofpacket Output 1
add_interface_port out out_valid valid Output 1
add_interface_port out out_empty empty Output 2


# 
# connection point in
# 
add_interface in avalon_streaming end
set_interface_property in associatedClock clk_in
set_interface_property in associatedReset reset_in
set_interface_property in dataBitsPerSymbol 8
set_interface_property in errorDescriptor ""
set_interface_property in firstSymbolInHighOrderBits true
set_interface_property in maxChannel 0
set_interface_property in readyLatency 0
set_interface_property in ENABLED true
set_interface_property in EXPORT_OF ""
set_interface_property in PORT_NAME_MAP ""
set_interface_property in CMSIS_SVD_VARIABLES ""
set_interface_property in SVD_ADDRESS_GROUP ""

add_interface_port in in_ready ready Output 1
add_interface_port in in_valid valid Input 1
add_interface_port in in_data data Input 32
add_interface_port in in_startofpacket startofpacket Input 1
add_interface_port in in_endofpacket endofpacket Input 1
add_interface_port in in_empty empty Input 2


# 
# connection point address
# 
add_interface address conduit end
set_interface_property address associatedClock clk_in
set_interface_property address associatedReset ""
set_interface_property address ENABLED true
set_interface_property address EXPORT_OF ""
set_interface_property address PORT_NAME_MAP ""
set_interface_property address CMSIS_SVD_VARIABLES ""
set_interface_property address SVD_ADDRESS_GROUP ""

add_interface_port address address address Input 32


# 
# connection point reset_in
# 
add_interface reset_in reset end
set_interface_property reset_in associatedClock clk_in
set_interface_property reset_in synchronousEdges DEASSERT
set_interface_property reset_in ENABLED true
set_interface_property reset_in EXPORT_OF ""
set_interface_property reset_in PORT_NAME_MAP ""
set_interface_property reset_in CMSIS_SVD_VARIABLES ""
set_interface_property reset_in SVD_ADDRESS_GROUP ""

add_interface_port reset_in reset_n reset_n Input 1


# 
# connection point clk_in
# 
add_interface clk_in clock end
set_interface_property clk_in clockRate 0
set_interface_property clk_in ENABLED true
set_interface_property clk_in EXPORT_OF ""
set_interface_property clk_in PORT_NAME_MAP ""
set_interface_property clk_in CMSIS_SVD_VARIABLES ""
set_interface_property clk_in SVD_ADDRESS_GROUP ""

add_interface_port clk_in clk clk Input 1

