transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlib dircc_system_node_dual_hps
vmap dircc_system_node_dual_hps dircc_system_node_dual_hps
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/dircc_system_node_dual_hps.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_mem_if_hhp_qseq_synth_top.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_reset_controller.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/conduit_avalon_mm_bridge.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_HPS.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_HPS_hps_io.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_mm_interconnect_0.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_avalon_st_adapter.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_avalon_st_adapter_001.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_cpu.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_cpu_cpu.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_cpu_cpu_debug_slave_sysclk.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_cpu_cpu_debug_slave_tck.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_cpu_cpu_debug_slave_wrapper.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_cpu_cpu_test_bench.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_fifo_in.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_fifo_out.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_jtag_uart.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_mem.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_mm_interconnect_0.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_timer.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_routing.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_1.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_1_processing.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_1_processing_mem.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_1_routing.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_pll.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/hps_sdram.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/hps_sdram_p0_acv_hard_addr_cmd_pads.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/hps_sdram_p0_acv_hard_io_pads.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/hps_sdram_p0_acv_hard_memphy.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/hps_sdram_p0_acv_ldc.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/hps_sdram_p0_altdqdqs.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/hps_sdram_p0_clock_pair_generator.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/hps_sdram_p0_generic_ddio.v}
vlog -sv -work work +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga {/home/patrick/Documents/Coursework/DiRCC/fpga/DE1_SoC.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altdq_dqs2_acv_connect_to_hard_phy_cyclonev.sv}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_avalon_st_clock_crosser.v}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_avalon_st_handshake_clock_crosser.v}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_mem_if_dll_cyclonev.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_mem_if_hard_memory_controller_top_cyclonev.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_mem_if_oct_cyclonev.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_merlin_address_alignment.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_merlin_axi_master_ni.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_merlin_burst_adapter_13_1.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_merlin_master_agent.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_merlin_master_translator.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_merlin_traffic_limiter.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_merlin_width_adapter.sv}
vlog -vlog01compat -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/altera_std_synchronizer_nocut.v}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_address_gen.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_router.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_HPS_fpga_interfaces.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_HPS_hps_io_border.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_mm_interconnect_0_router.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_mm_interconnect_0_router_002.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_avalon_st_adapter_001_timing_adapter_0.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_avalon_st_adapter_001_timing_adapter_0_fifo.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_avalon_st_adapter_timing_adapter_0.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_irq_mapper.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_mm_interconnect_0_cmd_demux_001.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_mm_interconnect_0_cmd_mux_001.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_mm_interconnect_0_router.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_mm_interconnect_0_router_001.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_mm_interconnect_0_router_002.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_mm_interconnect_0_router_003.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_processing_mm_interconnect_0_rsp_mux_001.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_routing_input_mux.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/dircc_system_node_dual_hps_node_0_routing_output_demux.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/hps_sdram_p0.sv}
vlog -sv -work dircc_system_node_dual_hps +incdir+/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules {/home/patrick/Documents/Coursework/DiRCC/fpga/db/ip/dircc_system_node_dual_hps/submodules/hps_sdram_pll.sv}

