	dircc_system_rtl_gals_test_version u0 (
		.clk_clk                   (<connected-to-clk_clk>),                   //             clk.clk
		.reset_reset_n             (<connected-to-reset_reset_n>),             //           reset.reset_n
		.node_0_mem_address        (<connected-to-node_0_mem_address>),        //      node_0_mem.address
		.node_0_mem_readdata       (<connected-to-node_0_mem_readdata>),       //                .readdata
		.node_0_mem_write          (<connected-to-node_0_mem_write>),          //                .write
		.node_0_mem_writedata      (<connected-to-node_0_mem_writedata>),      //                .writedata
		.node_1_mem_address        (<connected-to-node_1_mem_address>),        //      node_1_mem.address
		.node_1_mem_readdata       (<connected-to-node_1_mem_readdata>),       //                .readdata
		.node_1_mem_write          (<connected-to-node_1_mem_write>),          //                .write
		.node_1_mem_writedata      (<connected-to-node_1_mem_writedata>),      //                .writedata
		.node_2_mem_address        (<connected-to-node_2_mem_address>),        //      node_2_mem.address
		.node_2_mem_readdata       (<connected-to-node_2_mem_readdata>),       //                .readdata
		.node_2_mem_write          (<connected-to-node_2_mem_write>),          //                .write
		.node_2_mem_writedata      (<connected-to-node_2_mem_writedata>),      //                .writedata
		.node_65536_mem_address    (<connected-to-node_65536_mem_address>),    //  node_65536_mem.address
		.node_65536_mem_readdata   (<connected-to-node_65536_mem_readdata>),   //                .readdata
		.node_65536_mem_write      (<connected-to-node_65536_mem_write>),      //                .write
		.node_65536_mem_writedata  (<connected-to-node_65536_mem_writedata>),  //                .writedata
		.node_65537_mem_address    (<connected-to-node_65537_mem_address>),    //  node_65537_mem.address
		.node_65537_mem_readdata   (<connected-to-node_65537_mem_readdata>),   //                .readdata
		.node_65537_mem_write      (<connected-to-node_65537_mem_write>),      //                .write
		.node_65537_mem_writedata  (<connected-to-node_65537_mem_writedata>),  //                .writedata
		.node_65538_mem_address    (<connected-to-node_65538_mem_address>),    //  node_65538_mem.address
		.node_65538_mem_readdata   (<connected-to-node_65538_mem_readdata>),   //                .readdata
		.node_65538_mem_write      (<connected-to-node_65538_mem_write>),      //                .write
		.node_65538_mem_writedata  (<connected-to-node_65538_mem_writedata>),  //                .writedata
		.node_131072_mem_address   (<connected-to-node_131072_mem_address>),   // node_131072_mem.address
		.node_131072_mem_readdata  (<connected-to-node_131072_mem_readdata>),  //                .readdata
		.node_131072_mem_write     (<connected-to-node_131072_mem_write>),     //                .write
		.node_131072_mem_writedata (<connected-to-node_131072_mem_writedata>), //                .writedata
		.node_131073_mem_address   (<connected-to-node_131073_mem_address>),   // node_131073_mem.address
		.node_131073_mem_readdata  (<connected-to-node_131073_mem_readdata>),  //                .readdata
		.node_131073_mem_write     (<connected-to-node_131073_mem_write>),     //                .write
		.node_131073_mem_writedata (<connected-to-node_131073_mem_writedata>), //                .writedata
		.node_131074_mem_address   (<connected-to-node_131074_mem_address>),   // node_131074_mem.address
		.node_131074_mem_readdata  (<connected-to-node_131074_mem_readdata>),  //                .readdata
		.node_131074_mem_write     (<connected-to-node_131074_mem_write>),     //                .write
		.node_131074_mem_writedata (<connected-to-node_131074_mem_writedata>), //                .writedata
		.reset_13_reset_n          (<connected-to-reset_13_reset_n>),          //        reset_13.reset_n
		.node_3_mem_address        (<connected-to-node_3_mem_address>),        //      node_3_mem.address
		.node_3_mem_readdata       (<connected-to-node_3_mem_readdata>),       //                .readdata
		.node_3_mem_write          (<connected-to-node_3_mem_write>),          //                .write
		.node_3_mem_writedata      (<connected-to-node_3_mem_writedata>),      //                .writedata
		.node_4_mem_address        (<connected-to-node_4_mem_address>),        //      node_4_mem.address
		.node_4_mem_readdata       (<connected-to-node_4_mem_readdata>),       //                .readdata
		.node_4_mem_write          (<connected-to-node_4_mem_write>),          //                .write
		.node_4_mem_writedata      (<connected-to-node_4_mem_writedata>),      //                .writedata
		.node_5_mem_address        (<connected-to-node_5_mem_address>),        //      node_5_mem.address
		.node_5_mem_readdata       (<connected-to-node_5_mem_readdata>),       //                .readdata
		.node_5_mem_write          (<connected-to-node_5_mem_write>),          //                .write
		.node_5_mem_writedata      (<connected-to-node_5_mem_writedata>),      //                .writedata
		.node_6_mem_address        (<connected-to-node_6_mem_address>),        //      node_6_mem.address
		.node_6_mem_readdata       (<connected-to-node_6_mem_readdata>),       //                .readdata
		.node_6_mem_write          (<connected-to-node_6_mem_write>),          //                .write
		.node_6_mem_writedata      (<connected-to-node_6_mem_writedata>),      //                .writedata
		.node_7_mem_address        (<connected-to-node_7_mem_address>),        //      node_7_mem.address
		.node_7_mem_readdata       (<connected-to-node_7_mem_readdata>),       //                .readdata
		.node_7_mem_write          (<connected-to-node_7_mem_write>),          //                .write
		.node_7_mem_writedata      (<connected-to-node_7_mem_writedata>),      //                .writedata
		.node_8_mem_address        (<connected-to-node_8_mem_address>),        //      node_8_mem.address
		.node_8_mem_readdata       (<connected-to-node_8_mem_readdata>),       //                .readdata
		.node_8_mem_write          (<connected-to-node_8_mem_write>),          //                .write
		.node_8_mem_writedata      (<connected-to-node_8_mem_writedata>),      //                .writedata
		.node_65539_mem_address    (<connected-to-node_65539_mem_address>),    //  node_65539_mem.address
		.node_65539_mem_readdata   (<connected-to-node_65539_mem_readdata>),   //                .readdata
		.node_65539_mem_write      (<connected-to-node_65539_mem_write>),      //                .write
		.node_65539_mem_writedata  (<connected-to-node_65539_mem_writedata>),  //                .writedata
		.node_65540_mem_address    (<connected-to-node_65540_mem_address>),    //  node_65540_mem.address
		.node_65540_mem_readdata   (<connected-to-node_65540_mem_readdata>),   //                .readdata
		.node_65540_mem_write      (<connected-to-node_65540_mem_write>),      //                .write
		.node_65540_mem_writedata  (<connected-to-node_65540_mem_writedata>),  //                .writedata
		.node_65541_mem_address    (<connected-to-node_65541_mem_address>),    //  node_65541_mem.address
		.node_65541_mem_readdata   (<connected-to-node_65541_mem_readdata>),   //                .readdata
		.node_65541_mem_write      (<connected-to-node_65541_mem_write>),      //                .write
		.node_65541_mem_writedata  (<connected-to-node_65541_mem_writedata>),  //                .writedata
		.node_65542_mem_address    (<connected-to-node_65542_mem_address>),    //  node_65542_mem.address
		.node_65542_mem_readdata   (<connected-to-node_65542_mem_readdata>),   //                .readdata
		.node_65542_mem_write      (<connected-to-node_65542_mem_write>),      //                .write
		.node_65542_mem_writedata  (<connected-to-node_65542_mem_writedata>),  //                .writedata
		.node_65543_mem_address    (<connected-to-node_65543_mem_address>),    //  node_65543_mem.address
		.node_65543_mem_readdata   (<connected-to-node_65543_mem_readdata>),   //                .readdata
		.node_65543_mem_write      (<connected-to-node_65543_mem_write>),      //                .write
		.node_65543_mem_writedata  (<connected-to-node_65543_mem_writedata>),  //                .writedata
		.node_65544_mem_address    (<connected-to-node_65544_mem_address>),    //  node_65544_mem.address
		.node_65544_mem_readdata   (<connected-to-node_65544_mem_readdata>),   //                .readdata
		.node_65544_mem_write      (<connected-to-node_65544_mem_write>),      //                .write
		.node_65544_mem_writedata  (<connected-to-node_65544_mem_writedata>),  //                .writedata
		.node_131075_mem_address   (<connected-to-node_131075_mem_address>),   // node_131075_mem.address
		.node_131075_mem_readdata  (<connected-to-node_131075_mem_readdata>),  //                .readdata
		.node_131075_mem_write     (<connected-to-node_131075_mem_write>),     //                .write
		.node_131075_mem_writedata (<connected-to-node_131075_mem_writedata>), //                .writedata
		.node_131076_mem_address   (<connected-to-node_131076_mem_address>),   // node_131076_mem.address
		.node_131076_mem_readdata  (<connected-to-node_131076_mem_readdata>),  //                .readdata
		.node_131076_mem_write     (<connected-to-node_131076_mem_write>),     //                .write
		.node_131076_mem_writedata (<connected-to-node_131076_mem_writedata>), //                .writedata
		.node_131077_mem_address   (<connected-to-node_131077_mem_address>),   // node_131077_mem.address
		.node_131077_mem_readdata  (<connected-to-node_131077_mem_readdata>),  //                .readdata
		.node_131077_mem_write     (<connected-to-node_131077_mem_write>),     //                .write
		.node_131077_mem_writedata (<connected-to-node_131077_mem_writedata>), //                .writedata
		.node_131078_mem_address   (<connected-to-node_131078_mem_address>),   // node_131078_mem.address
		.node_131078_mem_readdata  (<connected-to-node_131078_mem_readdata>),  //                .readdata
		.node_131078_mem_write     (<connected-to-node_131078_mem_write>),     //                .write
		.node_131078_mem_writedata (<connected-to-node_131078_mem_writedata>), //                .writedata
		.node_131079_mem_address   (<connected-to-node_131079_mem_address>),   // node_131079_mem.address
		.node_131079_mem_readdata  (<connected-to-node_131079_mem_readdata>),  //                .readdata
		.node_131079_mem_write     (<connected-to-node_131079_mem_write>),     //                .write
		.node_131079_mem_writedata (<connected-to-node_131079_mem_writedata>), //                .writedata
		.node_131080_mem_address   (<connected-to-node_131080_mem_address>),   // node_131080_mem.address
		.node_131080_mem_readdata  (<connected-to-node_131080_mem_readdata>),  //                .readdata
		.node_131080_mem_write     (<connected-to-node_131080_mem_write>),     //                .write
		.node_131080_mem_writedata (<connected-to-node_131080_mem_writedata>)  //                .writedata
	);

